export type MDRUnformatted = {
  aprovadores?: string | null,
  cargos: string[],
  controlOp: string[],
  crit1Lesao: string[],
  crit31NaturDoRisc: string,
  crit41Prob: string,
  crit42SitControl: string,
  crit42Concentracao: string,
  crit44Exposicao: string,
  crit4Severidade: string,
  calculo: number,
  editores?: string | null,
  significanciaRisco: string,
  GHE?: string | null,
  linkAprovacao?: string | null,
  partesInteressadas?: string | null,
  perigo: string,
  responsavel?: string | null,
  risco: string,
  situacaoOp: string,
  tarefa: string,
  titulo: string,
  sectorProcesso: string,
  sectorUnidade: string,
  sectorArea: string,
}